FROM postgres:16.3

ENV POSTGRES_DB=ecom_db
ENV POSTGRES_USER=ecom_user
ENV POSTGRES_PASSWORD=ecom_pass

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./staticfiles /app/staticfiles
COPY ./media /app/media


EXPOSE 5432